"""Phase 5 audit run extensions

Revision ID: 653c9fed920d
Revises: d61e1973d40c
Create Date: 2026-10-06 18:16:56.523795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '653c9fed920d'
down_revision: Union[str, Sequence[str], None] = 'd61e1973d40c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_runs', sa.Column('trust_score', sa.Integer(), nullable=True))
    op.add_column('audit_runs', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('audit_runs', sa.Column('recommendation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_runs', 'recommendation')
    op.drop_column('audit_runs', 'summary')
    op.drop_column('audit_runs', 'trust_score')
    # ### end Alembic commands ###
