"""initial_schema_pull_requests_audit_runs_agent_findings

Revision ID: 70d4b60824c2
Revises: 
Create Date: 2026-10-07 18:30:17.620193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70d4b60824c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pull_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository', sa.String(length=255), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_branch', sa.String(length=255), nullable=True),
    sa.Column('target_branch', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('latest_commit_sha', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository', 'pr_number', name='uq_pull_requests_repository_pr_number')
    )
    op.create_index(op.f('ix_pull_requests_id'), 'pull_requests', ['id'], unique=False)
    op.create_index(op.f('ix_pull_requests_pr_number'), 'pull_requests', ['pr_number'], unique=False)
    op.create_index('ix_pull_requests_repo_pr', 'pull_requests', ['repository', 'pr_number'], unique=False)
    op.create_index(op.f('ix_pull_requests_repository'), 'pull_requests', ['repository'], unique=False)
    op.create_table('audit_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pull_request_id', sa.UUID(), nullable=False),
    sa.Column('commit_sha', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_runs_commit_sha'), 'audit_runs', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_audit_runs_id'), 'audit_runs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_runs_idempotency_key'), 'audit_runs', ['idempotency_key'], unique=True)
    op.create_index('ix_audit_runs_pr_commit', 'audit_runs', ['pull_request_id', 'commit_sha'], unique=False)
    op.create_index(op.f('ix_audit_runs_pull_request_id'), 'audit_runs', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_audit_runs_status'), 'audit_runs', ['status'], unique=False)
    op.create_table('agent_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_run_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_findings_agent_name'), 'agent_findings', ['agent_name'], unique=False)
    op.create_index('ix_agent_findings_audit_agent', 'agent_findings', ['audit_run_id', 'agent_name'], unique=False)
    op.create_index(op.f('ix_agent_findings_audit_run_id'), 'agent_findings', ['audit_run_id'], unique=False)
    op.create_index(op.f('ix_agent_findings_id'), 'agent_findings', ['id'], unique=False)
    op.create_index(op.f('ix_agent_findings_severity'), 'agent_findings', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_findings_severity'), table_name='agent_findings')
    op.drop_index(op.f('ix_agent_findings_id'), table_name='agent_findings')
    op.drop_index(op.f('ix_agent_findings_audit_run_id'), table_name='agent_findings')
    op.drop_index('ix_agent_findings_audit_agent', table_name='agent_findings')
    op.drop_index(op.f('ix_agent_findings_agent_name'), table_name='agent_findings')
    op.drop_table('agent_findings')
    op.drop_index(op.f('ix_audit_runs_status'), table_name='audit_runs')
    op.drop_index(op.f('ix_audit_runs_pull_request_id'), table_name='audit_runs')
    op.drop_index('ix_audit_runs_pr_commit', table_name='audit_runs')
    op.drop_index(op.f('ix_audit_runs_idempotency_key'), table_name='audit_runs')
    op.drop_index(op.f('ix_audit_runs_id'), table_name='audit_runs')
    op.drop_index(op.f('ix_audit_runs_commit_sha'), table_name='audit_runs')
    op.drop_table('audit_runs')
    op.drop_index(op.f('ix_pull_requests_repository'), table_name='pull_requests')
    op.drop_index('ix_pull_requests_repo_pr', table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_pr_number'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_id'), table_name='pull_requests')
    op.drop_table('pull_requests')
    # ### end Alembic commands ###
