"""add_users_auth_accounts_projects_feature_analyses

Revision ID: 79a4b960b2f5
Revises: 70d4b60824c2
Create Date: 2026-10-07 19:29:13.279616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import models


# revision identifiers, used by Alembic.
revision: str = '79a4b960b2f5'
down_revision: Union[str, Sequence[str], None] = '70d4b60824c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', models.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('auth_accounts',
    sa.Column('id', models.GUID(), nullable=False),
    sa.Column('user_id', models.GUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_account_id', name='uq_auth_accounts_provider_account')
    )
    op.create_index(op.f('ix_auth_accounts_id'), 'auth_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_auth_accounts_provider'), 'auth_accounts', ['provider'], unique=False)
    op.create_index(op.f('ix_auth_accounts_provider_account_id'), 'auth_accounts', ['provider_account_id'], unique=False)
    op.create_index(op.f('ix_auth_accounts_user_id'), 'auth_accounts', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', models.GUID(), nullable=False),
    sa.Column('user_id', models.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('repository_url', sa.String(length=1000), nullable=True),
    sa.Column('default_branch', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_index('ix_projects_user_name', 'projects', ['user_id', 'name'], unique=False)
    op.create_table('feature_analyses',
    sa.Column('id', models.GUID(), nullable=False),
    sa.Column('project_id', models.GUID(), nullable=False),
    sa.Column('user_id', models.GUID(), nullable=False),
    sa.Column('feature_description', sa.Text(), nullable=False),
    sa.Column('feasibility_score', sa.Float(), nullable=False),
    sa.Column('complexity_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=False),
    sa.Column('implementation_plan', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('complexity_score >= 0 AND complexity_score <= 100', name='chk_feature_complexity_score'),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 100', name='chk_feature_confidence_score'),
    sa.CheckConstraint('feasibility_score >= 0 AND feasibility_score <= 100', name='chk_feature_feasibility_score'),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 100', name='chk_feature_risk_score'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_analyses_id'), 'feature_analyses', ['id'], unique=False)
    op.create_index('ix_feature_analyses_proj_user', 'feature_analyses', ['project_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_feature_analyses_project_id'), 'feature_analyses', ['project_id'], unique=False)
    op.create_index(op.f('ix_feature_analyses_user_id'), 'feature_analyses', ['user_id'], unique=False)
    op.add_column('agent_findings', sa.Column('language', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_agent_findings_language'), 'agent_findings', ['language'], unique=False)
    op.add_column('pull_requests', sa.Column('project_id', models.GUID(), nullable=True))
    op.create_index(op.f('ix_pull_requests_project_id'), 'pull_requests', ['project_id'], unique=False)
    op.create_foreign_key('fk_pull_requests_project_id', 'pull_requests', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('fk_pull_requests_project_id', 'pull_requests', type_='foreignkey')
    op.drop_index(op.f('ix_pull_requests_project_id'), table_name='pull_requests')
    op.drop_column('pull_requests', 'project_id')
    op.drop_index(op.f('ix_agent_findings_language'), table_name='agent_findings')
    op.drop_column('agent_findings', 'language')
    op.drop_index(op.f('ix_feature_analyses_user_id'), table_name='feature_analyses')
    op.drop_index(op.f('ix_feature_analyses_project_id'), table_name='feature_analyses')
    op.drop_index('ix_feature_analyses_proj_user', table_name='feature_analyses')
    op.drop_index(op.f('ix_feature_analyses_id'), table_name='feature_analyses')
    op.drop_table('feature_analyses')
    op.drop_index('ix_projects_user_name', table_name='projects')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_auth_accounts_user_id'), table_name='auth_accounts')
    op.drop_index(op.f('ix_auth_accounts_provider_account_id'), table_name='auth_accounts')
    op.drop_index(op.f('ix_auth_accounts_provider'), table_name='auth_accounts')
    op.drop_index(op.f('ix_auth_accounts_id'), table_name='auth_accounts')
    op.drop_table('auth_accounts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
